version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8990:8990"
    depends_on:
      - db
    command:
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8990"